# Generated by Django 2.1.7 on 2019-03-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('server', 'SERVER'), ('host', 'HOST'), ('bartender', 'BARTENDER')], default='server', max_length=20)),
                ('photo_url', models.TextField()),
                ('sales', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_sections', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('manager', 'MANAGER'), ('general_manager', 'GENERAL_MANAGER'), ('assistant_manager', 'ASSISTANT_MANAGER')], default='manager', max_length=30)),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(choices=[('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('friday', 'FRIDAY'), ('saturday', 'SATURDAY'), ('sunday', 'SUNDAY')], default='monday', max_length=20)),
                ('am_staff_num', models.IntegerField()),
                ('aft_staff_num', models.IntegerField()),
                ('pm_staff_num', models.IntegerField()),
                ('am_sec_num', models.IntegerField()),
                ('aft_sec_num', models.IntegerField()),
                ('pm_sec_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('red', 'RED'), ('orange', 'ORANGE'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('purple', 'PURPLE')], default='red', max_length=20)),
                ('num_of_tables', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='scheduler.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('am', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('aft', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('pm', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='scheduler.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_am', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('mon_aft', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('mon_pm', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('tue_am', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('tue_aft', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('tue_pm', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('wed_am', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('wed_aft', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('wed_pm', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('thu_am', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('thu_aft', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('thu_pm', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('fri_am', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('fri_aft', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('fri_pm', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('sat_am', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('sat_aft', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('sat_pm', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('sun_am', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('sun_aft', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('sun_pm', models.CharField(choices=[('I am available', 'I AM AVAILABLE'), ('I am not available', 'I AM NOT AVAILABLE')], default='I am available', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='scheduler.Employee')),
            ],
        ),
    ]
