# Generated by Django 2.1.7 on 2019-03-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20190311_2014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FloorPlan',
        ),
    ]
