# Generated by Django 2.1.7 on 2019-03-11 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_delete_floorplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleByShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('AM', 'Morning Shift'), ('AFT', 'Afternoon Shift'), ('PM', 'Evening Shift')], max_length=30)),
                ('num_of_sections', models.IntegerField()),
                ('section_red', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scheduler.Employee')),
            ],
        ),
        migrations.DeleteModel(
            name='ScheduleByDay',
        ),
    ]
