# Generated by Django 2.1.7 on 2019-03-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20190311_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulebyshift',
            name='section_red',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='scheduler.Employee'),
        ),
    ]
