# Generated by Django 2.1.7 on 2019-03-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_auto_20190312_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailability',
            name='pm',
        ),
    ]
