# Generated by Django 2.1.7 on 2019-03-12 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_remove_unavailability_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='employee',
        ),
        migrations.AddField(
            model_name='schedulebyshift',
            name='section_blue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blue', to='scheduler.Employee'),
        ),
        migrations.AddField(
            model_name='schedulebyshift',
            name='section_green',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='green', to='scheduler.Employee'),
        ),
        migrations.AddField(
            model_name='schedulebyshift',
            name='section_orange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orange', to='scheduler.Employee'),
        ),
        migrations.AddField(
            model_name='schedulebyshift',
            name='section_purple',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purple', to='scheduler.Employee'),
        ),
        migrations.AddField(
            model_name='schedulebyshift',
            name='section_yellow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='yellow', to='scheduler.Employee'),
        ),
        migrations.AddField(
            model_name='section',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='shift',
            field=models.CharField(choices=[('AM', 'Morning Shift'), ('AFT', 'Afternoon Shift'), ('PM', 'Evening Shift')], default='AM', max_length=30),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='pm',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedulebyshift',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulebyshift',
            name='section_red',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='red', to='scheduler.Employee'),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='aft',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='am',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='fri_aft',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='fri_am',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='fri_pm',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='mon_aft',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='mon_am',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='mon_pm',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sat_aft',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sat_am',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sat_pm',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sun_aft',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sun_am',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sun_pm',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='thu_aft',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='thu_am',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='thu_pm',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='tue_aft',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='tue_am',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='tue_pm',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='wed_aft',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='wed_am',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='wed_pm',
            field=models.CharField(choices=[(True, 'I AM available'), (False, 'I am NOT available')], default='available', max_length=20),
        ),
    ]
