# Generated by Django 2.1.7 on 2019-03-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20190312_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailability',
            name='aft',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='am',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='pm',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='fri_aft',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='fri_am',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='fri_pm',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='mon_aft',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='mon_am',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='mon_pm',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sat_aft',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sat_am',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sat_pm',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sun_aft',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sun_am',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='sun_pm',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='thu_aft',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='thu_am',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='thu_pm',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='tue_aft',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='tue_am',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='tue_pm',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='wed_aft',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='wed_am',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='wed_pm',
            field=models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30),
        ),
    ]
