# Generated by Django 2.1.7 on 2019-03-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20190314_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulebyshift',
            name='section_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red', to='scheduler.Employee'),
        ),
    ]
