# Generated by Django 2.1.7 on 2019-03-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('server', 'Server'), ('host', 'Host'), ('bartender', 'Bartender')], default='server', max_length=20)),
                ('photo_url', models.TextField()),
                ('sales', models.IntegerField()),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('general_manager', 'General Manager'), ('assistant_manager', 'Assistant Manager')], default='manager', max_length=30)),
                ('photo_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleByShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('shift', models.CharField(choices=[('AM', 'Morning Shift'), ('AFT', 'Afternoon Shift'), ('PM', 'Evening Shift')], max_length=30)),
                ('num_of_sections', models.IntegerField()),
                ('section_blue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue', to='scheduler.Employee')),
                ('section_green', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='green', to='scheduler.Employee')),
                ('section_orange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orange', to='scheduler.Employee')),
                ('section_purple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purple', to='scheduler.Employee')),
                ('section_red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red', to='scheduler.Employee')),
                ('section_yellow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yellow', to='scheduler.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('shift', models.CharField(choices=[('AM', 'Morning Shift'), ('AFT', 'Afternoon Shift'), ('PM', 'Evening Shift')], default='AM', max_length=30)),
                ('color', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple')], default='red', max_length=20)),
                ('num_of_tables', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('am', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('aft', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('pm', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailability', to='scheduler.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_am', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('mon_aft', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('mon_pm', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('tue_am', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('tue_aft', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('tue_pm', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('wed_am', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('wed_aft', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('wed_pm', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('thu_am', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('thu_aft', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('thu_pm', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('fri_am', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('fri_aft', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('fri_pm', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('sat_am', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('sat_aft', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('sat_pm', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('sun_am', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('sun_aft', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('sun_pm', models.CharField(choices=[('available', 'I AM available'), ('unavailable', 'I am NOT available')], default='available', max_length=30)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='scheduler.Employee')),
            ],
        ),
    ]
