# Generated by Django 2.1.7 on 2019-03-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('server', 'Server'), ('host', 'Host'), ('bartender', 'Bartender')], max_length=20, null=True),
        ),
    ]
